name: Deploy to Hostinger

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to Hostinger (example)
        run: echo "Pretend we deploy here"
