name: Release

on:
  push:
    branches:
      - development

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set permissions for semantic-release
        run: chmod +x ./node_modules/.bin/semantic-release
      - name: Install dependencies
        run: npm install
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release